#!/usr/bin/env python3
"""站点总验收：**一条命令，exit 0 才算过**。

设计：`docs/design/site-single-page.md`。只用 python3 标准库。

站点现在是**两页**：首页 `index.html` + 更新日志子页 `changelog.html`（生成物，
源是 `editor/vscode/CHANGELOG.md`，见 `scripts/gen-site-changelog.py`）。这里查什么
（每项一个名字，失败会指名）：

| 项 | 断言 |
|---|---|
| `pages`     | `site/` 下恰好这两页，没有 `_partials/` 之类的内部目录 |
| `sitemap`   | `sitemap.xml` 与真实页面集合**双向相等**（不悬空、不漏页） |
| `links`     | 每页的 `href`/`src` 都解析得到：相对路径文件存在；锚点（含跨页锚点）有对应 `id` |
| `css-urls`  | CSS 里每个 `url(...)` 指向的文件存在（自托管字体） |
| `version`   | 每页都有版本回填钩子；除生成物外**没有写死的版本号**（`0.x.y` 字面量） |
| `meta`      | 每页 head 里 `lang`/`title`/`description`/`canonical`/`viewport`/`favicon`/`og:*` 齐全，且只允许一段内联 script |
| `markup`    | 标签配对（`html.parser` 走一遍）；没有内联 `style=` 属性 |
| `assets`    | 位图**只允许**头图 `assets/hero-vscode.png`（且有体积预算、宽高比与 `<img>` 属性一致）；html+css+js 在预算内 |
| `data`      | `site/data/site.json` 与最新**已发布 tag** 一致（`gen-site-data.py --check`） |
| `changelog` | `changelog.html` 与 `CHANGELOG.md` **逐字节一致**（`gen-site-changelog.py --check`） |
| `render`    | （`--browser`）真 Chrome 跑两页：资源零 404，且版本号被 JS 回填进 DOM |\n| `layout`    | （`--browser`）真 Chrome 量横向溢出：两页 × 4 个宽度，`scrollWidth` 不许超过视口 |

用法：

```bash
python3 scripts/check-site.py              # 默认 10 项（不需要浏览器）
python3 scripts/check-site.py --browser    # 额外跑渲染实跑（要 Chrome）
python3 scripts/check-site.py --json       # 机器可读
```

退出码：**0** 全绿 / **1** 有断言判红 / **3** 无法判定（缺 tag、缺文件）。
"""

from __future__ import annotations

import argparse
import json
import os
import re
import struct
import subprocess
import sys
from html.parser import HTMLParser

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SITE = os.path.join(REPO_ROOT, "site")
INDEX = os.path.join(SITE, "index.html")
CHANGELOG = os.path.join(SITE, "changelog.html")
DATA = os.path.join(SITE, "data", "site.json")

# 页面集合：**恰好这两页**。加页面的时候，sitemap 与这里要一起改（check_sitemap 会双向对账）。
PAGES = ["index.html", "changelog.html"]

# 体积预算（原始字节，不含字体）。它是"再加一个页面/一个库之前，先想想"的闸门。
SIZE_BUDGET = 120 * 1024
# 头图是**真截图**（不是装饰位图），所以有位图预算：一张、有上限。
HERO = "assets/hero-vscode.png"
HERO_BUDGET = 400 * 1024
BITMAP_EXT = (".png", ".jpg", ".jpeg", ".gif", ".webp", ".avif", ".bmp", ".ico")

# 写死的版本号：拒 IP（127.0.0.1），抓 `v0.62.0` 与 `0.62.0`。
VERSION_LITERAL = re.compile(r"(?<![\d.])0\.\d+\.\d+(?![\d.])")
# 版本引用必须走这些钩子，值由 site.js 从 data/site.json 回填。
VERSION_HOOKS = ("data-site-version", "data-version-text", "data-version-href")
# 生成物的标记：这类文件的内容**整段**来自另一个源（changelog 里当然有历史版本号），
# 所以跳过"写死版本号"这一条 —— 但它的**一致性**由 changelog 项逐字节守住。
GENERATED_MARK = "generated by scripts/gen-site-changelog.py"
GENERATED = [CHANGELOG]

TEXT_EXT = (".html", ".css", ".js", ".txt", ".xml", ".json", ".svg")


class Failure(Exception):
    pass


def rel(path: str) -> str:
    return os.path.relpath(path, REPO_ROOT)


def walk_site() -> list[str]:
    out: list[str] = []
    for root, dirs, files in os.walk(SITE):
        dirs[:] = [d for d in dirs if d not in (".git",)]
        for name in files:
            out.append(os.path.join(root, name))
    return sorted(out)


def read(path: str) -> str:
    with open(path, encoding="utf-8") as handle:
        return handle.read()


# ── HTML 解析：标签配对 + 引用收集 ─────────────────────────────────────

VOID = {"area", "base", "br", "col", "embed", "hr", "img", "input", "link",
        "meta", "param", "source", "track", "wbr"}


class PageParser(HTMLParser):
    def __init__(self) -> None:
        super().__init__(convert_charrefs=True)
        self.stack: list[tuple[str, int]] = []
        self.errors: list[str] = []
        self.refs: list[tuple[str, str, int]] = []   # (attr, value, line)
        self.ids: set[str] = set()
        self.inline_styles: list[int] = []
        self.meta: dict[str, str] = {}
        self.images: list[dict] = []

    def handle_starttag(self, tag, attrs):
        attrs = dict(attrs)
        line = self.getpos()[0]
        if tag not in VOID:
            self.stack.append((tag, line))
        if "id" in attrs:
            self.ids.add(attrs["id"])
        if "style" in attrs:
            self.inline_styles.append(line)
        for attr in ("href", "src"):
            if attr in attrs:
                self.refs.append((attr, attrs[attr], line))
        if tag == "img":
            self.images.append({"src": attrs.get("src", ""), "width": attrs.get("width"),
                                "height": attrs.get("height"), "alt": attrs.get("alt"), "line": line})
        if tag == "html" and "lang" in attrs:
            self.meta["lang"] = attrs["lang"]
        if tag == "meta":
            key = attrs.get("name") or attrs.get("property")
            if key:
                self.meta[key] = attrs.get("content", "")
        if tag == "link" and "rel" in attrs:
            self.meta[f"link:{attrs['rel']}"] = attrs.get("href", "")
        if tag == "title":
            self.meta["_in_title"] = "1"
        if tag == "script" and "src" not in attrs:
            self.meta.setdefault("inline_scripts", "0")
            self.meta["inline_scripts"] = str(int(self.meta["inline_scripts"]) + 1)

    def handle_endtag(self, tag):
        if tag in VOID:
            return
        if not self.stack:
            self.errors.append(f"第 {self.getpos()[0]} 行：多余的 </{tag}>")
            return
        open_tag, line = self.stack.pop()
        if open_tag != tag:
            self.errors.append(f"第 {line} 行 <{open_tag}> 与第 {self.getpos()[0]} 行 </{tag}> 不配对")
        if tag == "title" and self.stack:
            self.meta.pop("_in_title", None)

    def handle_data(self, data):
        if self.meta.pop("_in_title", None):
            self.meta["title"] = data.strip()

    def close(self):
        super().close()
        for tag, line in self.stack:
            self.errors.append(f"第 {line} 行 <{tag}> 没有闭合")


def parse_pages() -> dict[str, PageParser]:
    parsed: dict[str, PageParser] = {}
    for name in PAGES:
        path = os.path.join(SITE, name)
        if not os.path.exists(path):
            raise Failure(f"缺页面 {name}（跑 scripts/gen-site-changelog.py 补 changelog.html）")
        parser = PageParser()
        parser.feed(read(path))
        parser.close()
        parsed[name] = parser
    return parsed


# ── 各项断言 ───────────────────────────────────────────────────────────

def check_pages(files: list[str]) -> str:
    pages = sorted(os.path.basename(f) for f in files if f.endswith(".html"))
    if pages != sorted(PAGES):
        raise Failure(f"site/ 下应当恰好 {sorted(PAGES)}，实际：{pages}")
    internal = [rel(f) for f in files if os.sep + "_" in f]
    if internal:
        raise Failure(f"发布树里不该有内部目录（_partials 之类）：{internal}")
    return f"{len(PAGES)} 页（{', '.join(PAGES)}）"


def check_sitemap(files: list[str]) -> str:
    path = os.path.join(SITE, "sitemap.xml")
    if not os.path.exists(path):
        raise Failure("缺 site/sitemap.xml")
    locs = re.findall(r"<loc>([^<]+)</loc>", read(path))
    if not locs:
        raise Failure("sitemap.xml 里一条 <loc> 都没有")
    if len(locs) != len(set(locs)):
        raise Failure("sitemap.xml 里有重复 URL")
    # 双向：页面集合必须与 loc 集合一一对应。
    pages = {os.path.basename(f) for f in files if f.endswith(".html")}
    listed = {u.rstrip("/").rsplit("/", 1)[-1] or "index.html" for u in locs}
    listed = {name if name.endswith(".html") else "index.html" for name in listed}
    if pages != listed:
        raise Failure(f"sitemap 与真实页面不一致：页面 {sorted(pages)} vs sitemap {sorted(listed)}")
    return f"{len(locs)} 条，与页面集合双向相等"


def check_links(pages: dict[str, PageParser]) -> str:
    checked = 0
    for name, parser in pages.items():
        for attr, value, line in parser.refs:
            if value.startswith(("http://", "https://", "mailto:", "data:")):
                continue
            if value.startswith("#"):
                anchor = value[1:]
                if anchor and anchor not in parser.ids:
                    raise Failure(f"{name}:{line}：锚点 #{anchor} 在本页没有对应 id")
                checked += 1
                continue
            target = value.split("#", 1)[0].split("?", 1)[0]
            anchor = value.split("#", 1)[1] if "#" in value else ""
            if not target:
                continue
            resolved = os.path.normpath(os.path.join(SITE, target))
            if not os.path.exists(resolved):
                raise Failure(f"{name}:{line}：{attr}=\"{value}\" 指向不存在的 {target}")
            if anchor and os.path.basename(resolved) in pages:
                if anchor not in pages[os.path.basename(resolved)].ids:
                    raise Failure(f"{name}:{line}：{target}#{anchor} 的目标页里没有 id={anchor}")
            checked += 1
    return f"{checked} 条站内引用全部可解析（含跨页锚点）"


def check_css_urls(files: list[str]) -> str:
    checked = 0
    for path in files:
        if not path.endswith(".css"):
            continue
        base = os.path.dirname(path)
        for url in re.findall(r"url\(\s*[\"']?([^\"')]+)[\"']?\s*\)", read(path)):
            if url.startswith(("http://", "https://", "data:")):
                continue
            if not os.path.exists(os.path.normpath(os.path.join(base, url))):
                raise Failure(f"{rel(path)}：url({url}) 指向不存在的文件")
            checked += 1
    return f"{checked} 个资源引用存在"


def check_version(files: list[str], pages: dict[str, PageParser]) -> str:
    generated = {os.path.abspath(p) for p in GENERATED}
    for name, parser in pages.items():
        if not any(hook in read(os.path.join(SITE, name)) for hook in VERSION_HOOKS):
            raise Failure(f"{name} 里没有任何版本引用钩子（data-site-version 等）——版本号只能由数据回填")
    offenders: list[str] = []
    for path in files:
        if not path.endswith(TEXT_EXT):
            continue
        if os.path.abspath(path) == os.path.abspath(DATA):
            continue          # 这一份**就是**版本号的来源
        if os.path.abspath(path) in generated:
            continue          # 生成物：历史版本号本来就该在（一致性由 changelog 项守）
        for num, line in enumerate(read(path).splitlines(), 1):
            if VERSION_LITERAL.search(line):
                offenders.append(f"{rel(path)}:{line}")
    if offenders:
        raise Failure("写死的版本号："
                      + "、".join(offenders)
                      + "（版本号只能由 site/data/site.json 回填）")
    return f"{len(VERSION_HOOKS)} 类钩子 × {len(PAGES)} 页，0 处写死"


def check_meta(pages: dict[str, PageParser]) -> str:
    required = ["lang", "title", "description", "viewport", "og:title", "og:description"]
    for name, parser in pages.items():
        missing = [k for k in required if not parser.meta.get(k)]
        if not parser.meta.get("link:canonical"):
            missing.append("canonical")
        if not parser.meta.get("link:icon"):
            missing.append("favicon")
        if missing:
            raise Failure(f"{name} 的 head 缺元数据：{missing}")
        if parser.meta.get("inline_scripts") != "1":
            raise Failure(f"{name}：内联 <script> 只允许 head 里那一段配色 bootstrap（防首帧闪烁）")
    return f"{len(required) + 2} 项 × {len(PAGES)} 页齐全"


def check_markup(pages: dict[str, PageParser]) -> str:
    for name, parser in pages.items():
        if parser.errors:
            raise Failure(f"{name} 标签不配对：" + "；".join(parser.errors[:4]))
        if parser.inline_styles:
            raise Failure(f"{name}：内联 style= 出现在第 {parser.inline_styles} 行（样式只能进 site.css）")
    return f"两页标签配对，无内联样式"


def png_size(path: str) -> tuple[int, int]:
    with open(path, "rb") as handle:
        head = handle.read(24)
    if head[:8] != b"\x89PNG\r\n\x1a\n":
        raise Failure(f"{rel(path)} 不是 PNG")
    return struct.unpack(">II", head[16:24])


def check_assets(files: list[str], pages: dict[str, PageParser]) -> str:
    bitmaps = {os.path.relpath(f, SITE): f for f in files if f.lower().endswith(BITMAP_EXT)}
    unexpected = [k for k in bitmaps if k != HERO]
    if unexpected:
        raise Failure(f"位图只允许头图 {HERO}（它必须由 scripts/site-screenshot.mjs 生成）：{unexpected}")
    detail = "零位图"
    if HERO in bitmaps:
        size = os.path.getsize(bitmaps[HERO])
        if size > HERO_BUDGET:
            raise Failure(f"{HERO} 有 {size} 字节，超过头图预算 {HERO_BUDGET}")
        width, height = png_size(bitmaps[HERO])
        # 宽高比必须与首页 <img> 上写的 width/height 一致：否则图会被压扁，而这一点
        # 光看页面是看不出来的（"数据对了 ≠ 用户看见对了"）。
        img = next((i for i in pages["index.html"].images if i["src"].endswith("hero-vscode.png")), None)
        if img is None:
            raise Failure(f"{HERO} 在 index.html 里没有被引用")
        if not img["width"] or not img["height"]:
            raise Failure("头图 <img> 必须写 width/height（否则首屏会跳版）")
        want = float(img["width"]) / float(img["height"])
        got = width / height
        if abs(want - got) / got > 0.01:
            raise Failure(f"头图宽高比 {got:.3f}（{width}×{height}）与 <img width/height> 的 {want:.3f} 不一致")
        if not (img["alt"] or "").strip():
            raise Failure("头图必须有 alt")
        detail = f"头图 {HERO} {size // 1024} KB（预算 {HERO_BUDGET // 1024} KB，{width}×{height}）"
    total = sum(os.path.getsize(f) for f in files if f.endswith((".html", ".css", ".js")))
    if total > SIZE_BUDGET:
        raise Failure(f"html+css+js 共 {total} 字节，超过预算 {SIZE_BUDGET}")
    return f"{detail}；html+css+js {total} 字节（预算 {SIZE_BUDGET}）"


def run_script(args: list[str]) -> subprocess.CompletedProcess:
    return subprocess.run([sys.executable] + args, cwd=REPO_ROOT, capture_output=True, text=True)


def check_data() -> str:
    proc = run_script([os.path.join(REPO_ROOT, "scripts", "gen-site-data.py"), "--check"])
    if proc.returncode == 3:
        raise Failure("解析不出已发布 tag（浅克隆缺 tag？）—— 无法判定，不判绿")
    if proc.returncode != 0:
        raise Failure((proc.stderr or proc.stdout).strip())
    return (proc.stdout or "").strip().removeprefix("site data: ")


def check_changelog() -> str:
    proc = run_script([os.path.join(REPO_ROOT, "scripts", "gen-site-changelog.py"), "--check"])
    if proc.returncode != 0:
        raise Failure((proc.stderr or proc.stdout).strip())
    return (proc.stdout or "").strip().removeprefix("changelog: ")


# ── 渲染实跑（可选）───────────────────────────────────────────────────

def find_chrome() -> str | None:
    for candidate in (
        "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome",
        "google-chrome", "google-chrome-stable", "chromium", "chromium-browser",
    ):
        if os.path.sep in candidate:
            if os.path.exists(candidate):
                return candidate
        else:
            from shutil import which
            found = which(candidate)
            if found:
                return found
    return None


def _dump_dom(chrome: str, url: str, budget: int = 5000, timeout: int = 30) -> str:
    """跑一次**旧版** headless Chrome，返回 DOM。

    为什么用旧版 headless：macOS 上 `--headless=new` + `--dump-dom` 会挂住不返回（实测 120s）。
    为什么用 `--virtual-time-budget` 而不是 `--timeout`：后者会在 `fetch("data/site.json")`
    落定**之前**就把 DOM 倒出来，于是"版本号已回填"时红时绿（实测 4 次命中 vs 0 次）。
    为什么不等进程退出：macOS 上 Chrome 打完完整 DOM 之后**进程不退出** ⇒ 判据是"DOM 到齐
    了没有"（见到 `</html>` 就杀），不是"进程结束了没有"。
    """
    import shutil
    import tempfile
    import threading
    import time

    profile = tempfile.mkdtemp(prefix="soko-chrome-")
    try:
        proc = subprocess.Popen([
            chrome, "--headless", "--disable-gpu", "--no-sandbox",
            "--no-first-run", "--no-default-browser-check",
            "--disable-extensions", "--disable-background-networking",
            "--disable-sync", "--hide-scrollbars",
            f"--user-data-dir={profile}", f"--virtual-time-budget={budget}",
            "--dump-dom", url,
        ], stdout=subprocess.PIPE, stderr=subprocess.DEVNULL, text=True)
        chunks: list[str] = []

        def pump():
            for line in proc.stdout or ():
                chunks.append(line)

        threading.Thread(target=pump, daemon=True).start()
        deadline = time.time() + timeout
        while time.time() < deadline:
            if "</html>" in "".join(chunks) or proc.poll() is not None:
                break
            time.sleep(0.1)
        dom = "".join(chunks)
        if proc.poll() is None:
            proc.kill()
        try:
            proc.wait(timeout=10)
        except subprocess.TimeoutExpired:
            pass
        return dom
    finally:
        shutil.rmtree(profile, ignore_errors=True)


# 布局探针：在**真浏览器**里把每页按几个宽度装进 iframe，量 `scrollWidth` 与视口宽度。
# 为什么非要真浏览器：横向溢出的成因在排版（`100vw` 计算、不可断行的长标识符、负 margin
# 悬挑），静态检查看不见 —— 实测就是这么抓到两个（CHANGELOG 里一条 836px 的测试路径把
# 整页撑宽、`.wide` 的 margin-inline 被组件自己的 margin 简写覆盖）。
LAYOUT_WIDTHS = [360, 768, 1024, 1440]


def _layout_probe(widths: list[int]) -> str:
    return f"""<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><title>layout</title></head>
<body><pre id="out">pending</pre>
<script>
(async () => {{
  const pages = {json.dumps(PAGES)}, widths = {json.dumps(widths)}, out = [];
  for (const page of pages) for (const w of widths) {{
    const f = document.createElement('iframe');
    f.style.cssText = 'width:' + w + 'px;height:900px;border:0';
    f.src = page;
    document.body.appendChild(f);
    await new Promise((r) => {{ f.onload = r; }});
    await new Promise((r) => setTimeout(r, 80));
    out.push({{ page: page, width: w, inner: f.contentWindow.innerWidth,
               scrollW: f.contentDocument.documentElement.scrollWidth }});
    f.remove();
  }}
  document.getElementById('out').textContent = JSON.stringify(out);
}})();
</script></body></html>"""


class _SiteServer:
    """只读站点服务器（HTTP/1.0 + 多线程）+ 一条 `/__layout__` 探针路由。

    ⚠ **不要**改成 HTTP/1.1：keep-alive 会让 Chrome 认为还有未完成的网络活动，
    `--virtual-time-budget` 于是永远走不完 ⇒ 挂死。默认 HTTP/1.0（响应完即关连接）
    才能让虚拟时间正常推进。**必须多线程**：Chrome 会开一条不说话的预连接，单线程
    服务器一旦轮询到它就会卡在 `readline()` 上，把后面真正的请求全挡住。
    """

    def __init__(self) -> None:
        import http.server
        import threading

        self.missing: list[str] = []
        outer = self

        class Handler(http.server.SimpleHTTPRequestHandler):
            def __init__(self, *a, **kw):
                super().__init__(*a, directory=SITE, **kw)

            def log_message(self, fmt, *a):
                pass

            def send_error(self, code, message=None, explain=None):
                outer.missing.append(self.path)
                super().send_error(code, message, explain)

            def do_GET(self):
                if self.path.startswith("/__layout__"):
                    body = _layout_probe(LAYOUT_WIDTHS).encode("utf-8")
                    self.send_response(200)
                    self.send_header("content-type", "text/html; charset=utf-8")
                    self.send_header("content-length", str(len(body)))
                    self.end_headers()
                    self.wfile.write(body)
                    return
                super().do_GET()

        self.httpd = http.server.ThreadingHTTPServer(("127.0.0.1", 0), Handler)
        self.httpd.daemon_threads = True
        self.port = self.httpd.server_address[1]
        threading.Thread(target=self.httpd.serve_forever, daemon=True).start()

    def url(self, path: str) -> str:
        return f"http://127.0.0.1:{self.port}/{path}"

    def shutdown(self) -> None:
        self.httpd.shutdown()


def check_render() -> str:
    """真 Chrome 跑**两页**：资源零 404，且版本号被 JS 回填进 DOM。"""
    chrome = find_chrome()
    if not chrome:
        raise Failure("找不到 Chrome（--browser 需要它）")
    try:
        version = json.loads(read(DATA)).get("version", "")
    except (OSError, json.JSONDecodeError):
        version = ""
    if not version:
        raise Failure("site/data/site.json 里没有 version，无法验证回填")

    server = _SiteServer()
    try:
        for name in PAGES:
            dom = _dump_dom(chrome, server.url(name))
            if not dom.strip():
                raise Failure(f"{name}：Chrome 没有输出 DOM（进程可能起不来）")
            if f">{version}<" not in dom.replace(" ", ""):
                raise Failure(f"{name}：DOM 里没找到回填后的版本号 {version}（site.js 没跑或被缓存）")
        if server.missing:
            raise Failure(f"渲染时有 404：{sorted(set(server.missing))[:5]}")
    finally:
        server.shutdown()
    return f"Chrome 渲染 {len(PAGES)} 页通过，版本 {version} 已回填，资源零 404"


def check_layout() -> str:
    """真 Chrome 量**横向溢出**：每页 × 几个宽度，`scrollWidth` 不许超过视口。"""
    import html as html_mod

    chrome = find_chrome()
    if not chrome:
        raise Failure("找不到 Chrome（--browser 需要它）")
    server = _SiteServer()
    try:
        dom = _dump_dom(chrome, server.url("__layout__"), budget=20000, timeout=60)
    finally:
        server.shutdown()
    found = re.search(r'<pre id="out">(.*?)</pre>', dom, re.S)
    if not found or found.group(1).strip() in ("", "pending"):
        raise Failure("布局探针没跑完（DOM 里没有结果）—— 探针本身坏了，不判绿")
    rows = json.loads(html_mod.unescape(found.group(1)))
    bad = [r for r in rows if r["scrollW"] > r["inner"] + 1]
    if bad:
        raise Failure("这些宽度下页面横向溢出："
                      + "、".join(f'{r["page"]}@{r["width"]}（内容 {r["scrollW"]}px > 视口 {r["inner"]}px）' for r in bad))
    return f"{len(PAGES)} 页 × {len(LAYOUT_WIDTHS)} 个宽度（{LAYOUT_WIDTHS}）零横向溢出"


# ── 主流程 ─────────────────────────────────────────────────────────────

CHECKS = [
    ("pages", lambda files, pages: check_pages(files)),
    ("sitemap", lambda files, pages: check_sitemap(files)),
    ("links", lambda files, pages: check_links(pages)),
    ("css-urls", lambda files, pages: check_css_urls(files)),
    ("version", lambda files, pages: check_version(files, pages)),
    ("meta", lambda files, pages: check_meta(pages)),
    ("markup", lambda files, pages: check_markup(pages)),
    ("assets", lambda files, pages: check_assets(files, pages)),
    ("data", lambda files, pages: check_data()),
    ("changelog", lambda files, pages: check_changelog()),
]


def main(argv: list[str] | None = None) -> int:
    parser_args = argparse.ArgumentParser(description="站点总验收（首页 + 更新日志子页）")
    parser_args.add_argument("--browser", action="store_true", help="额外跑真 Chrome 渲染检查")
    parser_args.add_argument("--json", dest="as_json", action="store_true", help="机器可读输出")
    args = parser_args.parse_args(argv)

    if not os.path.exists(INDEX):
        print(f"site: 找不到 {rel(INDEX)}", file=sys.stderr)
        return 3

    files = walk_site()
    try:
        pages = parse_pages()
    except Failure as error:
        print(f"site: {error}", file=sys.stderr)
        return 1

    results: list[dict] = []
    failed = False
    for name, fn in CHECKS:
        try:
            results.append({"check": name, "ok": True, "detail": fn(files, pages)})
        except Failure as error:
            results.append({"check": name, "ok": False, "detail": str(error)})
            failed = True

    if args.browser:
        for name, fn in (("render", check_render), ("layout", check_layout)):
            try:
                results.append({"check": name, "ok": True, "detail": fn()})
            except Failure as error:
                results.append({"check": name, "ok": False, "detail": str(error)})
                failed = True

    if args.as_json:
        print(json.dumps({"ok": not failed, "checks": results}, ensure_ascii=False, indent=2))
    else:
        for row in results:
            print(f"  {'✓' if row['ok'] else '✗'} {row['check']:<10} {row['detail']}")
        total = len(results)
        green = sum(1 for row in results if row["ok"])
        print(f"site: {'ok' if not failed else 'FAILED'}（{green}/{total}）")

    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main())
