#!/usr/bin/env python3
"""site/changelog.html 生成器 —— **从 `editor/vscode/CHANGELOG.md` 生成**，不许手写。

为什么单独一个生成器（而不是写死在页面里）：这份 CHANGELOG 是**一个事实的唯一来源**
（每发一个版本，`editor/vscode/CHANGELOG.md` 就多一节）。手抄一份到站点上，第一次
忘记同步就会写出"线上写着 0.86、仓库已经是 0.87"的假话 —— 所以页面是生成物：

    python3 scripts/gen-site-changelog.py            # 重写 site/changelog.html
    python3 scripts/gen-site-changelog.py --check    # 只校验（与磁盘逐字节一致）

`site/changelog.html` 里带一行生成标记；`scripts/check-site.py` 的 `changelog`
项会重新生成一次并**逐字节比对** —— 所以"忘了重新生成"会判红，而不是悄悄漂移。

为什么只放最近 N 个版本：站点有 120 KB 的体积预算（`check-site.py` 的 `assets`
项），而整份 CHANGELOG 是 160 KB 量级的 Markdown。页面上给最近 `--limit`（默认 **7**）
个版本的正文 + 一个"更早的版本"直链（指仓库里的 `CHANGELOG.md`）。
**为什么是 7**（2026-10-09）：加上中英文自动识别（每页一份英文文案字典）与 topbar 的
图标/语言/GitHub 控件后站点体积顶到 120 KB 预算 ⇒ 按"预算不抬、从内容侧省"的纪律
一路从 10 收到 8、再收到 **7**（每减一版约省 7 KB）✓。

用法：

    python3 scripts/gen-site-changelog.py [--out site/changelog.html] [--limit 12] [--check]
"""

from __future__ import annotations

import argparse
import html
import json
import os
import re
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SOURCE = os.path.join(REPO_ROOT, "editor", "vscode", "CHANGELOG.md")
DEFAULT_OUT = os.path.join(REPO_ROOT, "site", "changelog.html")
REPO_URL = "https://github.com/ColorlessBoy/sokonanoda-lang"

MARKER = "<!-- generated by scripts/gen-site-changelog.py from editor/vscode/CHANGELOG.md -->"

HEAD = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">

<title>更新日志 · sokonanoda</title>
<meta name="description" content="sokonanoda 的更新日志：最近 {limit} 个版本改了什么（由仓库里的 CHANGELOG.md 生成）。">
<link rel="canonical" href="https://colorlessboy.github.io/sokonanoda-lang/changelog.html">
<meta name="theme-color" content="#f5f7f9" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0f1216" media="(prefers-color-scheme: dark)">
<meta property="og:type" content="article">
<meta property="og:title" content="更新日志 · sokonanoda">
<meta property="og:description" content="最近 {limit} 个版本改了什么（由仓库里的 CHANGELOG.md 生成）。">
<meta property="og:url" content="https://colorlessboy.github.io/sokonanoda-lang/changelog.html">
<meta property="og:locale" content="zh_CN">
<link rel="icon" href="favicon.svg" type="image/svg+xml">

<link rel="stylesheet" href="assets/fonts.css">
<link rel="stylesheet" href="assets/site.css">

<!-- 首帧防闪烁：在 CSS 之前把用户选过的配色贴上 <html>。 -->
<script>try{{var t=localStorage.getItem("soko-theme");if(t&&t!=="system")document.documentElement.setAttribute("data-theme",t)}}catch(e){{}}</script>
</head>

<body>
<a class="skip-link" href="#main" data-i18n="skip">跳到正文</a>

<header class="site-header">
  <div class="wrap">
    <a class="brand" href="./">sokonanoda <small data-i18n="brandTag">形式化证明教学语言</small></a>
    <nav aria-label="页面内导航">
      <ul>
        <li><a href="index.html#what" data-i18n="navWhat">它是什么</a></li>
        <li><a href="index.html#start" data-i18n="navStart">怎么开始</a></li>
        <li><a href="index.html#courses" data-i18n="navCourses">教材</a></li>
      </ul>
    </nav>
    <!-- 主题按钮用**图标**（用户 2026-10-09）：文字版「跟随系统」四个字、「浅色/深色」两个字
         ⇒ 切换时按钮宽度会跳；图标三种状态同宽，且 `aria-label` 仍把状态与动作说全 ✓。
         图标由 CSS 按 `:root[data-theme]` 选，`site.js` 只管 `aria-label`。 -->
    <!-- 控件组：**必须包一层**（用户 2026-10-09：「两个方框不在一条水平线上」）——
         头部是 `align-items: baseline`，而图标按钮没有文字基线 ⇒ 它与带文字的按钮
         按**不同的基线**对齐，必然错位 ✗。包一层 + `align-items: center` 让组内自己
         对齐，`align-self: center` 让整组在头部行里居中。 -->
    <span class="header-controls">
    <button class="theme-toggle icon-toggle" type="button" data-theme-toggle aria-pressed="false"
            data-i18n-aria="themeToggleLabel" aria-label="配色：跟随系统（点击切换）">
      <svg class="ico ico-system" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true" focusable="false"><circle cx="8" cy="8" r="5.4" fill="none" stroke="currentColor" stroke-width="1.4"/><path d="M8 2.6a5.4 5.4 0 0 0 0 10.8Z" fill="currentColor"/></svg>
      <svg class="ico ico-light" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true" focusable="false"><circle cx="8" cy="8" r="3.1" fill="none" stroke="currentColor" stroke-width="1.4"/><path d="M8 1v2.1M8 12.9V15M1 8h2.1M12.9 8H15M3.05 3.05l1.48 1.48M11.47 11.47l1.48 1.48M12.95 3.05l-1.48 1.48M4.53 11.47l-1.48 1.48" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linecap="round"/></svg>
      <svg class="ico ico-dark" viewBox="0 0 16 16" width="16" height="16" aria-hidden="true" focusable="false"><path d="M13.4 9.8A5.7 5.7 0 0 1 6.2 2.6a5.7 5.7 0 1 0 7.2 7.2Z" fill="none" stroke="currentColor" stroke-width="1.4" stroke-linejoin="round"/></svg>
    </button>
    <button class="theme-toggle lang-toggle" type="button" data-lang-toggle hidden
            data-i18n="langToggle" data-i18n-aria="langToggleLabel"
            aria-label="切换到英文">EN</button>
    <!-- GitHub 仓库（用户 2026-10-09：topbar 缺它）。文字而不是图标：预算是硬约束
         （html+css+js 只剩几百字节），而 `GitHub` 是专名、不用翻译 ✓。 -->
    <a class="theme-toggle gh-link" href="https://github.com/ColorlessBoy/sokonanoda-lang" data-i18n-aria="ghLabel" aria-label="GitHub 仓库">GitHub</a>
    </span>
  </div>
</header>

<main id="main">

  <section class="section">
    <div class="wrap">
      <h1 data-i18n="changelogTitle">更新日志</h1>
      <p class="lead" data-i18n="changelogLead">
        每次发版改了什么。<strong>这一页是生成物</strong>：正文来自仓库里的
        <a href="{repo}/blob/main/editor/vscode/CHANGELOG.md"><code>editor/vscode/CHANGELOG.md</code></a>，
        这里只放最近 <strong>{limit}</strong> 个版本。
      </p>
      <p class="fact">
        <span data-i18n="changelogFactLead">当前发布版本</span>
        <span class="ver" data-site-version>当前发布版本</span><span data-i18n="changelogFactRest"> ·
        全部版本与逐条细节见 <a href="{repo}/blob/main/editor/vscode/CHANGELOG.md">完整 CHANGELOG</a> ·
        产物在 <a href="{repo}/releases">Releases</a>。</span>
      </p>

      <nav class="toc" aria-label="版本列表" data-i18n-aria="tocLabel">
        <ul>
"""

TAIL = """        </ul>
      </nav>
    </div>
  </section>
{entries}
</main>

<footer class="site-footer">
  <div class="wrap">
    <span><span data-i18n="footerVersion">版本</span> <span class="ver" data-site-version>当前发布版本</span> ·
      <a href="{repo}/blob/main/NOTICE.md">Apache-2.0</a></span>
    <nav aria-label="页脚">
      <ul>
        <li><a href="{repo}" data-i18n="footerSource">源码</a></li>
        <li><a href="{repo}/releases" data-i18n="footerReleases">Releases</a></li>
        <li><a href="changelog.html" aria-current="page">Changelog</a></li>
        <li><a href="index.html" data-i18n="footerBack">回到首页</a></li>
      </ul>
    </nav>
  </div>
</footer>

<!-- 英文文案字典：**纯数据**（不是可执行脚本），check-site.py 会解析它做键对齐判据。 -->
<script type="application/json" id="i18n-en">
{i18n}
</script>
<script src="assets/i18n.js"></script>
<script src="assets/site.js" defer></script>
</body>
</html>
"""


# ── 一小撮 Markdown → HTML（够用就好；不认识的一律当段落，绝不吞内容）──────────

def inline(text: str) -> str:
    r"""行内：`code`、**粗体**、*斜体*、[文字](链接)。先转义，再放行我们自己生成的标签。

    四个实测踩过的坑（前三个都会留下**不平衡的标签**，`check-site.py` 的 markup 项判红）：
      · `**… *which* …**`（粗体里套斜体）—— 粗体要**非贪婪**，且斜体要在**粗体内部**先解；
      · `… and *why***`（源里真有这个形状）—— 收尾那个不闭合的斜体要单独认，
        跟在 `</strong>` 后面的那颗多余星号要吃掉；
      · `` `SOKO_*` ``（**代码段里带星号**）—— 代码段必须先**换成占位符**，
        否则后面的斜体正则会跨过它、把半行吃成 `<em>`；
      · `` `未知子命令 \`rebuildd\`` ``（代码里带转义反引号）—— 先把 `\`` 藏成占位符。
    """
    out = html.escape(text, quote=False)
    out = out.replace("\\`", "\x00")

    codes: list[str] = []

    def stash(match: re.Match) -> str:
        codes.append(match.group(1))
        return f"\x01{len(codes) - 1}\x02"

    out = re.sub(r"`([^`]+)`", stash, out)
    out = re.sub(r"\*\*\*(.+?)\*\*\*", r"<strong><em>\1</em></strong>", out)

    def bold(match: re.Match) -> str:
        inner = re.sub(r"\*([^*\n]+)\*", r"<em>\1</em>", match.group(1))
        inner = re.sub(r"\*([^*\n]+)$", r"<em>\1</em>", inner)
        return "<strong>" + inner + "</strong>"

    out = re.sub(r"\*\*(.+?)\*\*", bold, out)
    out = out.replace("</strong>*", "</strong>")      # `*why***` 的第三颗星
    out = re.sub(r"(?<![\*\w])\*([^\*\n]+)\*(?!\*)", r"<em>\1</em>", out)
    out = re.sub(r"\[([^\]]+)\]\((https?://[^)\s]+)\)",
                 lambda m: f'<a href="{m.group(2)}">{m.group(1)}</a>', out)
    out = re.sub(r"\x01(\d+)\x02", lambda m: "<code>" + codes[int(m.group(1))] + "</code>", out)
    return out.replace("\x00", "`")


def plain(text: str) -> str:
    """给 id / 目录用的纯文本。"""
    return re.sub(r"\s+", " ", re.sub(r"[`*\[\]]|\(https?://[^)]+\)", "", text)).strip()


def parse_entries(markdown: str) -> list[dict]:
    """把 CHANGELOG.md 切成 [{version, date, blocks}]，保持文件里的顺序（新→旧）。"""
    lines = markdown.splitlines()
    heads = [(i, m) for i, line in enumerate(lines)
             if (m := re.match(r"^## \[?([0-9][^\]\s]*)\]?\s*[—–-]\s*(\S+)\s*$", line))]
    entries = []
    for n, (start, m) in enumerate(heads):
        end = heads[n + 1][0] if n + 1 < len(heads) else len(lines)
        entries.append({"version": m.group(1), "date": m.group(2), "blocks": parse_blocks(lines[start + 1:end])})
    return entries


def parse_blocks(lines: list[str]) -> list[tuple]:
    """切块：`###` 小标题 / `>` 摘要 / `-` 列表（含两层）/ 段落。

    列表的两种续行都要认：**没有标记的缩进续行**（一条 bullet 写三行，实测很常见）
    与**嵌套 bullet**。续行归到"最近的那一条"上；缩进比它深的归到子项上。
    """
    blocks: list[tuple] = []
    i = 0
    while i < len(lines):
        raw = lines[i]
        stripped = raw.strip()
        if not stripped:
            i += 1
            continue
        if stripped.startswith("### "):
            blocks.append(("h3", stripped[4:].strip()))
            i += 1
            continue
        if stripped.startswith(">"):
            quote: list[str] = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                quote.append(lines[i].strip().lstrip(">").strip())
                i += 1
            blocks.append(("quote", " ".join(x for x in quote if x)))
            continue
        if re.match(r"^\s*[-*] ", raw):
            items: list[dict] = []
            while i < len(lines):
                line = lines[i]
                if not line.strip():
                    nxt = lines[i + 1] if i + 1 < len(lines) else ""
                    if re.match(r"^\s*[-*] ", nxt):
                        i += 1
                        continue
                    break
                m = re.match(r"^(\s*)[-*] (.*)$", line)
                if m:
                    indent, body = len(m.group(1)), m.group(2).strip()
                    if indent >= 2 and items:
                        items[-1]["kids"].append({"text": body, "indent": indent})
                    else:
                        items.append({"text": body, "indent": indent, "kids": []})
                    i += 1
                    continue
                if not items:
                    break
                indent = len(line) - len(line.lstrip())
                last = items[-1]
                if last["kids"] and indent > last["kids"][-1]["indent"] - 2:
                    last["kids"][-1]["text"] += " " + line.strip()
                else:
                    last["text"] += " " + line.strip()
                i += 1
            blocks.append(("ul", items))
            continue
        para: list[str] = []
        while i < len(lines) and lines[i].strip() and not re.match(r"^\s*([-*] |#{2,4} |> )", lines[i]):
            para.append(lines[i].strip())
            i += 1
        blocks.append(("p", " ".join(para)))
    return blocks


def render_blocks(blocks: list[tuple]) -> str:
    out: list[str] = []
    for block in blocks:
        kind = block[0]
        if kind == "h3":
            out.append(f"      <h3>{inline(block[1])}</h3>")
        elif kind == "quote":
            out.append(f'      <p class="lead">{inline(block[1])}</p>')
        elif kind == "p":
            out.append(f"      <p>{inline(block[1])}</p>")
        elif kind == "ul":
            out.append("      <ul>")
            for item in block[1]:
                out.append(f'        <li>{inline(item["text"])}')
                if item["kids"]:
                    out.append("          <ul>")
                    for kid in item["kids"]:
                        out.append(f'            <li>{inline(kid["text"])}</li>')
                    out.append("          </ul>")
                out.append("        </li>")
            out.append("      </ul>")
    return "\n".join(out)


def render(markdown: str, limit: int) -> str:
    entries = parse_entries(markdown)
    if not entries:
        raise SystemExit("change log: CHANGELOG.md 里一个版本节都没解析出来")
    recent = entries[:limit]
    rest = entries[limit:]

    toc = "\n".join(
        f'          <li><a href="#v{e["version"]}">v{e["version"]}</a>'
        f'<span class="tag">{html.escape(e["date"])}</span></li>'
        for e in recent
    )
    if rest:
        toc += (f'\n          <li><a href="{REPO_URL}/blob/main/editor/vscode/CHANGELOG.md" '
                f'data-i18n="tocOlder">更早的 {len(rest)} 个版本</a></li>')

    sections = []
    for e in recent:
        body = render_blocks(e["blocks"])
        sections.append(
            f'  <section class="section release" id="v{e["version"]}">\n'
            f'    <div class="wrap">\n'
            f'      <h2><span class="ver">v{e["version"]}</span> '
            f'<span class="tag">{html.escape(e["date"])}</span></h2>\n'
            f'{body}\n'
            f'    </div>\n'
            f'  </section>'
        )

    i18n = {
        "title": "Changelog · sokonanoda",
        "description": f"What changed in each sokonanoda release: the most recent {limit} versions, "
                       f"generated from editor/vscode/CHANGELOG.md in the repository.",
        "skip": "Skip to content",
        "brandTag": "a formal proof teaching language",
        "navWhat": "What it is",
        "navStart": "Getting started",
        "navCourses": "Courses",
        "themeToggleLabel": "Theme: System (click to change)",
        "langToggle": "中",
        "langToggleLabel": "Switch to Chinese",
        "ghLabel": "GitHub repository",
        "changelogTitle": "Changelog",
        "changelogLead": f"What changed in each release. <strong>This page is generated</strong>: the text comes from "
                          f'<a href="{REPO_URL}/blob/main/editor/vscode/CHANGELOG.md"><code>editor/vscode/CHANGELOG.md</code></a> '
                          f"in the repository, and only the most recent <strong>{limit}</strong> versions are shown here.",
        "changelogFactLead": "Current published version",
        "changelogFactRest": f' · every version and every detail is in the '
                             f'<a href="{REPO_URL}/blob/main/editor/vscode/CHANGELOG.md">full CHANGELOG</a> · '
                             f'artifacts are on <a href="{REPO_URL}/releases">Releases</a>.',
        "tocLabel": "Version list",
        "footerVersion": "version",
        "footerSource": "Source",
        "footerReleases": "Releases",
        "footerBack": "Back to the home page",
    }
    if rest:
        i18n["tocOlder"] = f"{len(rest)} older versions"

    page = HEAD.format(limit=limit, repo=REPO_URL)
    page += toc + "\n"
    page += TAIL.format(repo=REPO_URL, entries="\n".join(sections),
                        i18n=json.dumps(i18n, ensure_ascii=False, indent=2))
    return MARKER + "\n" + page


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="生成 site/changelog.html（源：editor/vscode/CHANGELOG.md）")
    ap.add_argument("--out", default=DEFAULT_OUT)
    ap.add_argument("--limit", type=int, default=7)
    ap.add_argument("--check", action="store_true", help="只校验：与磁盘上的文件逐字节一致？")
    args = ap.parse_args(argv)

    if not os.path.exists(SOURCE):
        print(f"changelog: 找不到 {os.path.relpath(SOURCE, REPO_ROOT)}", file=sys.stderr)
        return 3
    with open(SOURCE, encoding="utf-8") as handle:
        markdown = handle.read()
    page = render(markdown, args.limit)

    if args.check:
        if not os.path.exists(args.out):
            print(f"changelog: 缺 {os.path.relpath(args.out, REPO_ROOT)}（跑 scripts/gen-site-changelog.py）", file=sys.stderr)
            return 1
        with open(args.out, encoding="utf-8") as handle:
            on_disk = handle.read()
        if on_disk != page:
            print("changelog: 站点上的更新日志与 CHANGELOG.md 不一致（跑 scripts/gen-site-changelog.py 重生成）", file=sys.stderr)
            return 1
        print(f"changelog: 与 {os.path.relpath(SOURCE, REPO_ROOT)} 一致")
        return 0

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(page)
    print(f"changelog: 写入 {os.path.relpath(args.out, REPO_ROOT)}（{len(page)} 字节）")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
